# Generated by Django 2.2.1 on 2019-07-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cafeinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('address', models.CharField(max_length=120)),
                ('smoke', models.BooleanField()),
                ('opentime', models.TimeField()),
                ('closetime', models.TimeField()),
                ('atmosphere', models.CharField(max_length=500)),
            ],
        ),
    ]
