# Generated by Django 2.2.3 on 2019-07-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeinformation',
            name='menu',
            field=models.CharField(default='', editable=False, max_length=500),
        ),
    ]
