# Generated by Django 2.2.3 on 2019-07-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_cafeinformation_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeinformation',
            name='saclose',
            field=models.TimeField(default=''),
        ),
        migrations.AddField(
            model_name='cafeinformation',
            name='saopen',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='cafeinformation',
            name='menu',
            field=models.CharField(default='', max_length=500),
        ),
    ]
