# Generated by Django 2.2.3 on 2019-07-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190723_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeinformation',
            name='sunclose',
            field=models.TimeField(default=''),
        ),
        migrations.AddField(
            model_name='cafeinformation',
            name='sunopen',
            field=models.TimeField(default=''),
        ),
    ]
