# Generated by Django 2.2.3 on 2019-07-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190723_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafeinformation',
            old_name='othertime',
            new_name='other',
        ),
    ]
