# Generated by Django 2.2.3 on 2019-07-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190723_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeinformation',
            name='other',
        ),
    ]
