# Generated by Django 2.2.3 on 2019-07-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_cafeinformation_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeinformation',
            name='menu',
            field=models.CharField(default='', editable=False, max_length=500),
        ),
    ]
