# Generated by Django 2.2.3 on 2019-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190723_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeinformation',
            name='menu',
            field=models.CharField(default='', max_length=500),
        ),
    ]
