# Generated by Django 2.2.3 on 2019-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20190723_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeinformation',
            name='other',
            field=models.CharField(default='', max_length=500),
        ),
    ]
